# Generated by Django 4.0.10 on 2023-04-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0002_pageitem_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
