# Generated by Django 4.0.10 on 2023-04-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0005_alter_menuitem_icon_alter_pageitem_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageItem',
            new_name='SectionItem',
        ),
    ]
