# Generated by Django 4.0.10 on 2023-04-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0006_rename_pageitem_sectionitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionitem',
            old_name='page_title',
            new_name='section_title',
        ),
    ]
