# Generated by Django 4.0.10 on 2023-04-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0007_rename_page_title_sectionitem_section_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('editor', 'Can edit menues and sections'))},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, help_text='Go to https://fontawesome.com/v5/search to find matching icons. We only support free icons. Format example: fas fa-hand-spock', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='icon',
            field=models.CharField(blank=True, help_text='Go to https://fontawesome.com/v5/search to find matching icons. We only support free icons. Format example: fas fa-hand-spock', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='index',
            field=models.IntegerField(default=0, help_text='The entire wiki page is sorted by this index. The lower the value, the further to the top is the section.', unique=True),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='menu_name',
            field=models.CharField(help_text='Menu under which this section should be displayed.', max_length=255),
        ),
    ]
