# Generated by Django 4.0.10 on 2023-04-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0008_alter_general_options_alter_menuitem_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='name',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='path',
            field=models.CharField(help_text='The path of the URL. You will find that page under https://{your_auth_domain}/simplewiki/{name}.', max_length=255, null=True, unique=True),
        ),
    ]
