# Generated by Django 4.0.10 on 2023-04-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0009_remove_menuitem_name_menuitem_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='path',
            new_name='name',
        ),
    ]
