# Generated by Django 4.0.10 on 2023-04-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0013_alter_menuitem_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='group',
            field=models.CharField(blank=True, help_text="Optional: Do you only want to show this page to one group of people? Insert the group name here and only they will be able to see the post and all of it's sections.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional: Go to https://fontawesome.com/v5/search to find matching icons. We only support free icons. Format example: fas fa-hand-spock', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='index',
            field=models.IntegerField(default=0, help_text='Required: The navbar is sorted by this index. The lower the value, the further to the left is the menu.', unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='path',
            field=models.CharField(help_text='Required: The path of the URL. You will find that page under https://{your_auth_domain}/simplewiki/{name}.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(help_text='Required: The navbar title for the menu.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='content',
            field=models.TextField(blank=True, help_text='Optional: You can use HTML.', null=True),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional: Go to https://fontawesome.com/v5/search to find matching icons. We only support free icons. Format example: fas fa-hand-spock', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='index',
            field=models.IntegerField(default=0, help_text='Required: The entire wiki page is sorted by this index. The lower the value, the further to the top is the section.'),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='menu_name',
            field=models.CharField(help_text='Required: Menu under which this section should be displayed.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='section_title',
            field=models.CharField(help_text='Required: This title will be displayed above the content.', max_length=255, null=True),
        ),
    ]
