# Generated by Django 4.0.10 on 2023-04-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0015_rename_menu_name_sectionitem_menu_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionitem',
            old_name='section_title',
            new_name='title',
        ),
    ]
