# Generated by Django 4.0.10 on 2023-04-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0016_rename_section_title_sectionitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionitem',
            name='content',
            field=models.TextField(blank=True, help_text='Optional: This will be displayed as your main content of the section. You can use markdown. See https://commonmark.org/help/ for references.', null=True),
        ),
        migrations.AlterField(
            model_name='sectionitem',
            name='title',
            field=models.CharField(help_text='Required: This title will be displayed above the content.', max_length=255, null=True, unique=True),
        ),
    ]
