# Generated by Django 4.0.10 on 2023-04-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0018_rename_group_menuitem_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('editor_access', 'Can edit menues and sections'))},
        ),
    ]
