# Generated by Django 4.0.10 on 2023-10-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0020_menuitem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='index',
            field=models.IntegerField(default=0, help_text='Required: The navbar is sorted by this index. The lower the value, the further to the left is the menu.'),
        ),
    ]
