# Generated by Django 4.0.10 on 2023-11-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0021_alter_menuitem_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='states',
            field=models.CharField(blank=True, help_text="Optional: Do you only want to show this page to one state? Insert the state name here and only they will be able to see the post and all of it's sections.", max_length=255, null=True),
        ),
    ]
