# Generated by Django 4.0.10 on 2023-10-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0022_menuitem_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='groups',
            field=models.CharField(blank=True, help_text="Optional: Do you only want to show this page to one group of people? Insert the group name here and only they will be able to see the post and all of it's sections.", max_length=255),
        ),
    ]
