# Generated by Django 4.0.10 on 2023-11-14 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0022_menuitem_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('groups', models.CharField(blank=True, max_length=255)),
                ('states', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='simplewiki.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplewiki.menu')),
            ],
        ),
    ]
