# Generated by Django 4.0.10 on 2023-10-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0023_alter_menuitem_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional: Go to https://fontawesome.com/v5/search to find matching icons. We only support free icons. Format example: fas fa-hand-spock', max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.CharField(blank=True, help_text='Optional: Write the path of the parent menu. If you want this menu to be the parent leave this field empty.', max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='path',
            field=models.CharField(help_text='Required: The path of the URL. You will find that page under https://{your_auth_domain}/simplewiki/{name}.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='states',
            field=models.CharField(blank=True, help_text="Optional: Do you only want to show this page to one state? Insert the state name here and only they will be able to see the post and all of it's sections.", max_length=255),
        ),
    ]
