# Generated by Django 4.0.10 on 2023-11-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0024_alter_menu_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='index',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
