# Generated by Django 4.0.10 on 2023-11-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0026_alter_menu_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simplewiki.menu'),
        ),
    ]
