# Generated by Django 4.0.10 on 2024-02-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0027_alter_section_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='last_edut',
            field=models.TextField(blank=True),
        ),
    ]
