# Generated by Django 4.0.10 on 2024-02-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0030_alter_section_last_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='my_date',
            field=models.DateField(auto_now=True),
        ),
    ]
