# Generated by Django 4.0.10 on 2024-02-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0031_section_my_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='my_date',
            new_name='last_edit_date',
        ),
    ]
