# Generated by Django 4.0.10 on 2024-02-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplewiki', '0032_rename_my_date_section_last_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='last_edit_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
